/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWebModulesScriptsRouteImport } from './routes/_authenticated/web-modules/scripts'
import { Route as AuthenticatedWebModulesNiktoRouteImport } from './routes/_authenticated/web-modules/nikto'
import { Route as AuthenticatedWebModulesGatheringRouteImport } from './routes/_authenticated/web-modules/gathering'
import { Route as AuthenticatedWebModulesDirBustingRouteImport } from './routes/_authenticated/web-modules/dir-busting'
import { Route as AuthenticatedIpModulesTemplatesRouteImport } from './routes/_authenticated/ip-modules/templates'
import { Route as AuthenticatedIpModulesNmapRouteImport } from './routes/_authenticated/ip-modules/nmap'
import { Route as AuthenticatedApiModulesTestRouteImport } from './routes/_authenticated/api-modules/test'
import { Route as AuthenticatedApiModulesMappingRouteImport } from './routes/_authenticated/api-modules/mapping'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWebModulesScriptsRoute =
  AuthenticatedWebModulesScriptsRouteImport.update({
    id: '/web-modules/scripts',
    path: '/web-modules/scripts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWebModulesNiktoRoute =
  AuthenticatedWebModulesNiktoRouteImport.update({
    id: '/web-modules/nikto',
    path: '/web-modules/nikto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWebModulesGatheringRoute =
  AuthenticatedWebModulesGatheringRouteImport.update({
    id: '/web-modules/gathering',
    path: '/web-modules/gathering',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWebModulesDirBustingRoute =
  AuthenticatedWebModulesDirBustingRouteImport.update({
    id: '/web-modules/dir-busting',
    path: '/web-modules/dir-busting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIpModulesTemplatesRoute =
  AuthenticatedIpModulesTemplatesRouteImport.update({
    id: '/ip-modules/templates',
    path: '/ip-modules/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIpModulesNmapRoute =
  AuthenticatedIpModulesNmapRouteImport.update({
    id: '/ip-modules/nmap',
    path: '/ip-modules/nmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiModulesTestRoute =
  AuthenticatedApiModulesTestRouteImport.update({
    id: '/api-modules/test',
    path: '/api-modules/test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiModulesMappingRoute =
  AuthenticatedApiModulesMappingRouteImport.update({
    id: '/api-modules/mapping',
    path: '/api-modules/mapping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api-modules/mapping': typeof AuthenticatedApiModulesMappingRoute
  '/api-modules/test': typeof AuthenticatedApiModulesTestRoute
  '/ip-modules/nmap': typeof AuthenticatedIpModulesNmapRoute
  '/ip-modules/templates': typeof AuthenticatedIpModulesTemplatesRoute
  '/web-modules/dir-busting': typeof AuthenticatedWebModulesDirBustingRoute
  '/web-modules/gathering': typeof AuthenticatedWebModulesGatheringRoute
  '/web-modules/nikto': typeof AuthenticatedWebModulesNiktoRoute
  '/web-modules/scripts': typeof AuthenticatedWebModulesScriptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api-modules/mapping': typeof AuthenticatedApiModulesMappingRoute
  '/api-modules/test': typeof AuthenticatedApiModulesTestRoute
  '/ip-modules/nmap': typeof AuthenticatedIpModulesNmapRoute
  '/ip-modules/templates': typeof AuthenticatedIpModulesTemplatesRoute
  '/web-modules/dir-busting': typeof AuthenticatedWebModulesDirBustingRoute
  '/web-modules/gathering': typeof AuthenticatedWebModulesGatheringRoute
  '/web-modules/nikto': typeof AuthenticatedWebModulesNiktoRoute
  '/web-modules/scripts': typeof AuthenticatedWebModulesScriptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/api-modules/mapping': typeof AuthenticatedApiModulesMappingRoute
  '/_authenticated/api-modules/test': typeof AuthenticatedApiModulesTestRoute
  '/_authenticated/ip-modules/nmap': typeof AuthenticatedIpModulesNmapRoute
  '/_authenticated/ip-modules/templates': typeof AuthenticatedIpModulesTemplatesRoute
  '/_authenticated/web-modules/dir-busting': typeof AuthenticatedWebModulesDirBustingRoute
  '/_authenticated/web-modules/gathering': typeof AuthenticatedWebModulesGatheringRoute
  '/_authenticated/web-modules/nikto': typeof AuthenticatedWebModulesNiktoRoute
  '/_authenticated/web-modules/scripts': typeof AuthenticatedWebModulesScriptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api-modules/mapping'
    | '/api-modules/test'
    | '/ip-modules/nmap'
    | '/ip-modules/templates'
    | '/web-modules/dir-busting'
    | '/web-modules/gathering'
    | '/web-modules/nikto'
    | '/web-modules/scripts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api-modules/mapping'
    | '/api-modules/test'
    | '/ip-modules/nmap'
    | '/ip-modules/templates'
    | '/web-modules/dir-busting'
    | '/web-modules/gathering'
    | '/web-modules/nikto'
    | '/web-modules/scripts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/api-modules/mapping'
    | '/_authenticated/api-modules/test'
    | '/_authenticated/ip-modules/nmap'
    | '/_authenticated/ip-modules/templates'
    | '/_authenticated/web-modules/dir-busting'
    | '/_authenticated/web-modules/gathering'
    | '/_authenticated/web-modules/nikto'
    | '/_authenticated/web-modules/scripts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/web-modules/scripts': {
      id: '/_authenticated/web-modules/scripts'
      path: '/web-modules/scripts'
      fullPath: '/web-modules/scripts'
      preLoaderRoute: typeof AuthenticatedWebModulesScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/web-modules/nikto': {
      id: '/_authenticated/web-modules/nikto'
      path: '/web-modules/nikto'
      fullPath: '/web-modules/nikto'
      preLoaderRoute: typeof AuthenticatedWebModulesNiktoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/web-modules/gathering': {
      id: '/_authenticated/web-modules/gathering'
      path: '/web-modules/gathering'
      fullPath: '/web-modules/gathering'
      preLoaderRoute: typeof AuthenticatedWebModulesGatheringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/web-modules/dir-busting': {
      id: '/_authenticated/web-modules/dir-busting'
      path: '/web-modules/dir-busting'
      fullPath: '/web-modules/dir-busting'
      preLoaderRoute: typeof AuthenticatedWebModulesDirBustingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ip-modules/templates': {
      id: '/_authenticated/ip-modules/templates'
      path: '/ip-modules/templates'
      fullPath: '/ip-modules/templates'
      preLoaderRoute: typeof AuthenticatedIpModulesTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ip-modules/nmap': {
      id: '/_authenticated/ip-modules/nmap'
      path: '/ip-modules/nmap'
      fullPath: '/ip-modules/nmap'
      preLoaderRoute: typeof AuthenticatedIpModulesNmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-modules/test': {
      id: '/_authenticated/api-modules/test'
      path: '/api-modules/test'
      fullPath: '/api-modules/test'
      preLoaderRoute: typeof AuthenticatedApiModulesTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-modules/mapping': {
      id: '/_authenticated/api-modules/mapping'
      path: '/api-modules/mapping'
      fullPath: '/api-modules/mapping'
      preLoaderRoute: typeof AuthenticatedApiModulesMappingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedApiModulesMappingRoute: typeof AuthenticatedApiModulesMappingRoute
  AuthenticatedApiModulesTestRoute: typeof AuthenticatedApiModulesTestRoute
  AuthenticatedIpModulesNmapRoute: typeof AuthenticatedIpModulesNmapRoute
  AuthenticatedIpModulesTemplatesRoute: typeof AuthenticatedIpModulesTemplatesRoute
  AuthenticatedWebModulesDirBustingRoute: typeof AuthenticatedWebModulesDirBustingRoute
  AuthenticatedWebModulesGatheringRoute: typeof AuthenticatedWebModulesGatheringRoute
  AuthenticatedWebModulesNiktoRoute: typeof AuthenticatedWebModulesNiktoRoute
  AuthenticatedWebModulesScriptsRoute: typeof AuthenticatedWebModulesScriptsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedApiModulesMappingRoute: AuthenticatedApiModulesMappingRoute,
  AuthenticatedApiModulesTestRoute: AuthenticatedApiModulesTestRoute,
  AuthenticatedIpModulesNmapRoute: AuthenticatedIpModulesNmapRoute,
  AuthenticatedIpModulesTemplatesRoute: AuthenticatedIpModulesTemplatesRoute,
  AuthenticatedWebModulesDirBustingRoute:
    AuthenticatedWebModulesDirBustingRoute,
  AuthenticatedWebModulesGatheringRoute: AuthenticatedWebModulesGatheringRoute,
  AuthenticatedWebModulesNiktoRoute: AuthenticatedWebModulesNiktoRoute,
  AuthenticatedWebModulesScriptsRoute: AuthenticatedWebModulesScriptsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
